import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { fetchInsights, fetchPrediction } from '../slices/insightsSlice';
import PageHeader from '../components/PageHeader';
import SummaryCard from '../components/SummaryCard';
import ProgressBar from '../components/ProgressBar';
import Spinner from '../components/Spinner';
import Alert from '../components/Alert';
import EmptyState from '../components/EmptyState';
import { formatCurrency } from '../utils/format';
import { seriesColors } from '../utils/chartTheme';

/**
 * Badge showing which engine produced the insights. `heuristic` is a normal,
 * fully-supported state - not an error - so it is styled as information
 * rather than as a warning.
 */
function ProviderBadge({ provider }) {
  if (!provider) return null;

  const isAI = provider === 'openai';

  return (
    <span
      className={`chip ${isAI ? 'bg-primary-50 text-primary-700' : 'bg-plane text-ink-secondary ring-1 ring-inset ring-hairline'}`}
      title={
        isAI
          ? 'Generated by OpenAI gpt-4o-mini from your summary figures'
          : 'Generated by the built-in rules engine — no API key configured'
      }
    >
      <span aria-hidden="true">{isAI ? '✦' : '⚙'}</span>
      {isAI ? 'OpenAI' : 'Heuristic engine'}
    </span>
  );
}

export default function Insights() {
  const dispatch = useDispatch();
  const {
    insights,
    recommendations,
    provider,
    insightsSummary,
    insightsLoading,
    insightsError,
    prediction,
    predictionLoading
  } = useSelector((state) => state.insights);

  useEffect(() => {
    dispatch(fetchInsights());
    dispatch(fetchPrediction());
  }, [dispatch]);

  const refresh = () => {
    dispatch(fetchInsights());
    dispatch(fetchPrediction());
  };

  const hasData = (insightsSummary?.totalIncome || 0) + (insightsSummary?.totalExpense || 0) > 0;

  return (
    <>
      <PageHeader
        title="Insights"
        subtitle="Recommendations built from your own transactions — never from anyone else's."
      >
        <ProviderBadge provider={provider} />
        <button type="button" onClick={refresh} disabled={insightsLoading} className="btn-ghost">
          {insightsLoading ? 'Refreshing…' : 'Refresh'}
        </button>
      </PageHeader>

      {insightsError && (
        <Alert tone="error" className="mb-4" title="Could not generate insights">
          {insightsError}
        </Alert>
      )}

      {insightsLoading && insights.length === 0 ? (
        <Spinner label="Analysing your finances" />
      ) : !hasData ? (
        <EmptyState
          title="Nothing to analyse yet"
          description="Add some income and expenses and the engine will start finding patterns worth acting on."
          actionLabel="Add a transaction"
          actionTo="/transactions"
        />
      ) : (
        <>
          {/* ---- Forecast ------------------------------------------------ */}
          <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <SummaryCard
              label="Projected next-month expense"
              value={formatCurrency(prediction?.predictedExpense ?? insightsSummary?.predictedExpense ?? 0)}
              footnote={prediction?.basis || 'Mean of your monthly expense buckets'}
              accent={seriesColors.expense}
            />
            <SummaryCard
              label="Savings rate"
              value={`${insightsSummary?.savingsRate ?? 0}%`}
              footnote={`${formatCurrency(insightsSummary?.savings ?? 0)} saved overall`}
              accent={seriesColors.savings}
              tone={(insightsSummary?.savings ?? 0) >= 0 ? 'positive' : 'negative'}
            />
            <SummaryCard
              label="Top category"
              value={insightsSummary?.topCategory?.category || '—'}
              footnote={
                insightsSummary?.topCategory
                  ? `${formatCurrency(insightsSummary.topCategory.amount)} · ${insightsSummary.topCategory.percentage}% of spend`
                  : 'No expenses recorded'
              }
              accent={seriesColors.income}
            />
            <div className="card">
              <p className="text-sm font-medium text-ink-secondary">Forecast confidence</p>
              <p className="mt-2 text-2xl font-semibold tracking-tight text-ink sm:text-3xl">
                {predictionLoading ? '…' : `${prediction?.confidence ?? insightsSummary?.confidence ?? 55}%`}
              </p>
              <div className="mt-3">
                <ProgressBar percent={prediction?.confidence ?? insightsSummary?.confidence ?? 55} />
              </div>
              <p className="mt-1.5 text-xs text-ink-muted">Grows as you record more expenses</p>
            </div>
          </section>

          {prediction?.budgetRisk && (
            <Alert tone="warning" className="mt-4" title="Budget risk">
              Your projected spend of {formatCurrency(prediction.predictedExpense)} is above your{' '}
              {formatCurrency(prediction.monthlyBudget)} monthly budget. Trimming{' '}
              {formatCurrency(prediction.predictedExpense - prediction.monthlyBudget)} would bring you back inside it.
            </Alert>
          )}

          {/* ---- Insights + recommendations ------------------------------ */}
          <section className="mt-6 grid gap-4 lg:grid-cols-2">
            <div className="card">
              <div className="mb-4 flex items-center justify-between gap-3">
                <h2 className="text-sm font-semibold text-ink">What your numbers say</h2>
                <ProviderBadge provider={provider} />
              </div>

              <ul className="space-y-3">
                {insights.map((insight) => (
                  <li key={insight} className="flex gap-3 text-sm text-ink-secondary">
                    <span
                      aria-hidden="true"
                      className="mt-1.5 h-1.5 w-1.5 flex-none rounded-full bg-primary-500"
                    />
                    <span>{insight}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="card">
              <h2 className="mb-4 text-sm font-semibold text-ink">What to do next</h2>

              <ul className="space-y-3">
                {recommendations.map((recommendation, index) => (
                  <li key={recommendation} className="flex gap-3 text-sm text-ink-secondary">
                    <span
                      aria-hidden="true"
                      className="flex h-5 w-5 flex-none items-center justify-center rounded-full bg-accent-50 text-xs font-semibold text-accent-600"
                    >
                      {index + 1}
                    </span>
                    <span>{recommendation}</span>
                  </li>
                ))}
              </ul>

              <p className="mt-5 border-t border-hairline pt-3 text-xs text-ink-muted">
                Recommendations always come from the deterministic engine, so this panel works with or
                without an API key.
              </p>
            </div>
          </section>

          <p className="mt-4 text-xs text-ink-muted">
            {provider === 'openai'
              ? 'Only aggregate figures — totals, category shares, and monthly trends — are sent to OpenAI. Individual transactions never leave the server.'
              : 'No OpenAI key is configured, so insights come from the built-in rules engine. Add OPENAI_API_KEY to server/.env to switch on the AI-written version.'}
          </p>
        </>
      )}
    </>
  );
}
